### ISSUE TITLE
404 not found error

### ISSUE THREAD

**Issue by sirvon** [42matters/Profiler-SDK-Demo#1]
```java
10-05 13:49:15.778 3314-3431/com.teamxna.sirvon W/System.err: com.core42matters.android.profiler.InvalidApiCallException: {"status": "404 Not Found", "error": "device not found"}
10-05 13:49:15.778 3314-3431/com.teamxna.sirvon W/System.err:     at com.core42matters.android.profiler.e.a(SourceFile:116)
10-05 13:49:15.778 3314-3431/com.teamxna.sirvon W/System.err:     at com.core42matters.android.profiler.j.run(SourceFile:41)
10-05 13:49:15.778 3314-3431/com.teamxna.sirvon W/System.err:     at com.core42matters.android.profiler.n.handleMessage(SourceFile:47)
10-05 13:49:15.778 3314-3431/com.teamxna.sirvon W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-05 13:49:15.778 3314-3431/com.teamxna.sirvon W/System.err:     at android.os.Looper.loop(Looper.java:135)
10-05 13:49:15.778 3314-3431/com.teamxna.sirvon W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by 42matters** [comment]
1.2.4 improved on boarding so such warnings won't appear any more
